version: "3.8"
services:
  backoffice:
    build:
      context: ./backoffice
    image: droits-backoffice
    ports:
      - "5001:5001"
    environment:
      ASPNETCORE_URLS: "http://0.0.0.0:5001"
  webapp:
    build:
      context: ./webapp
    image: droits-webapp
    ports:
      - "3000:3000"
