version: "3.8"
services:
  backoffice:
    build:
      context: ./backoffice
    image: droits-backoffice
    ports:
      - "5000:5000"
      - "5001:5001"
    environment:
      ASPNETCORE_Kestrel__Certificates__Default__Password: "password"
      ASPNETCORE_Kestrel__Certificates__Default__Path: "/https/aspnetapp.pfx"
    volumes:
      - ~/.aspnet/https:/https:ro
  webapp:
    build:
      context: ./webapp
    image: droits-webapp
    ports:
      - "3000:3000"
