name: Backoffice pipeline - Development
on:
  push:
    branches:
      - main
jobs:
  deploy_dev:
    name: Deploy to Dev Environment
    uses: ./.github/workflows/backoffice-pipeline.yml
    with:
      environment: development
      terraform_workspace: dev
    secrets:
      registry_url: ${{ secrets.ECR_REPOSITORY_URL }}
      repository_name: ${{ secrets.ECR_REPOSITORY_NAME }}
      aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      aws_session_token: ${{ secrets.AWS_SESSION_TOKEN }}
      aws_account_number: ${{ secrets.AWS_ACCOUNT_NUMBER }}
      db_username: ${{ secrets.DB_USERNAME }}
      db_password: ${{ secrets.DB_PASSWORD }}
