name: Backoffice pipeline
on:
  workflow_call:
    inputs:
      environment:
        description: >
          The environment to which the application should be deployed.  Must be one of development/staging/production
          and must match the terraform_workspace input.
        type: string
        required: true
      terraform_workspace:
        description: >
          The Terraform workspace to which infrastructure should be deployed.  Must be one of dev/staging/production and
          must match the environment input.
        type: string
        required: true
    secrets:
      aws_access_key_id:
        required: true
      aws_secret_access_key:
        required: true
      aws_session_token:
        required: true
      aws_account_number:
        description: The account number in which infrastructure should be deployed
        required: true
      db_username:
        description: The username for the master db
        required: true
      db_password:
        description: The password for the master db
        required: true
      registry_url:
        description: The URL of the registry where the image should be published
        required: true
      repository_name:
        description: The name of the image to be published
        required: true
jobs:
  terraform_lint:
    name: Terraform lint
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    defaults:
      run:
        working-directory: terraform
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.2
      - name: Terraform Lint
        run: terraform fmt --recursive --check

  test:
    name: Test backoffice
    needs: [terraform_lint]
    uses: ./.github/workflows/backoffice-test.yml
    with:
      dotnet-version: "7.0.x"

  publish:
    name: Publish backoffice
    needs: [test]
    uses: ./.github/workflows/backoffice-publish.yml
    with:
      tag: latest
      environment: ${{ inputs.environment }}
    secrets:
      registry_url: ${{ secrets.ECR_REPOSITORY_URL }}
      repository_name: ${{ secrets.ECR_REPOSITORY_NAME }}
      aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      aws_session_token: ${{ secrets.AWS_SESSION_TOKEN }}

  deploy:
    name: ${{ inputs.environment }}
    needs: [publish]
    uses: ./.github/workflows/backoffice-deploy.yml
    with:
      environment: ${{ inputs.environment }}
      terraform_workspace: ${{ inputs.terraform_workspace }}
      version: ${{ github.sha }}
    secrets:
      registry_url: ${{ secrets.ECR_REPOSITORY_URL }}
      repository_name: ${{ secrets.ECR_REPOSITORY_NAME }}
      aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      aws_session_token: ${{ secrets.AWS_SESSION_TOKEN }}
      aws_account_number: ${{ secrets.AWS_ACCOUNT_NUMBER }}
      db_username: ${{ secrets.DB_USERNAME }}
      db_password: ${{ secrets.DB_PASSWORD }}
