name: Backoffice pipeline - Development
on:
  push:
    branches:
      - main
jobs:
  deploy_dev:
    name: Deploy to Dev Environment
    uses: ./.github/workflows/backoffice-pipeline.yml
    with:
      tag: ${{ github.sha }}
      environment: development
      terraform_workspace: dev
