name: Testing backoffice

on:
  workflow_call:
    inputs:
      dotnet-version:
        description: The dotnet version to use, e.g. '7.0.x'
        required: true
        type: string
      env_file:
        type: string
        description: The contents of the environment file
        required: true

defaults:
  run:
    working-directory: backoffice

jobs:
  unit_tests:
    name: Backoffice unit tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Setup dotnet
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ inputs.dotnet-version }}
        env-file: ${{ inputs.env_file }}
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build
    - name: Run tests
      run: dotnet test
