name: Destroy production infrastructure 
on:
  workflow_call:

jobs:
  run_pipeline:
    name: Destroy Production
    uses: ./.github/workflows/destroy.yml
    with:
      environment: production
      terraform_workspace: production
    secrets:
      registry_url: ${{ secrets.ECR_REPOSITORY_URL }}
      backoffice_repository_name: ${{ secrets.BACKOFFICE_ECR_REPOSITORY_NAME }}
      webapp_repository_name: ${{ secrets.WEBAPP_ECR_REPOSITORY_NAME }}
      aws_role_arn: ${{ secrets.AWS_ROLE_ARN }}
      aws_account_number: ${{ secrets.AWS_ACCOUNT_NUMBER }}
      db_username: ${{ secrets.DB_USERNAME }}
      db_password: ${{ secrets.DB_PASSWORD }}
      webapp_env_file: ${{ secrets.WEBAPP_ENV_FILE }}
      backoffice_env_file: ${{ secrets.BACKOFFICE_ENV_FILE }}
      alerts_email: ${{ secrets.ALERTS_EMAIL }}