name: Testing webapp

on:
  workflow_call:
    inputs:
      working-directory:
        description: The directory to publish
        type: string
        required: true
  pull_request:
    branches:
      - main

jobs:
  unit_tests:
    name: Webapp unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 14.19.2
          
      - name: Set up env vars
        env:
          WEBAPP_ENV_FILE: ${{ secrets.TESTING_WEBAPP_ENV_FILE }}
        run: |
          cd webapp
          echo "$WEBAPP_ENV_FILE" > .env.json

      - name: Install NPM dependencies
        run: |
          cd webapp
          npm install --dev

      - name: Run tests
        run: |
          cd webapp
          npm run test
