name: Testing webapp

on:
  workflow_call:
    inputs:
      working-directory:
        description: The directory to publish
        type: string
        required: true

jobs:
  unit_tests:
    name: Webapp unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 14.19.2

      - name: Install NPM dependencies
        run: |
          cd webapp
          npm install --dev

      - name: Run tests
        run: |
          cd webapp
          npm run test
