name: Testing webapp

on:
  workflow_call:

defaults:
  run:
    working-directory: ./spike-webapp

jobs:
  unit_tests:
    name: Webapp unit tests
    runs-on: ubuntu-latest

    steps:
    - name: Run tests
      run: |
        echo "To-do - Add tests"
